version: "3"
services:
  app:
    build:
      args:
        - PYTHON_VERSION=3.11.7
      context: .
      dockerfile: "Dockerfile"
    volumes:
      - .:/app
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [utility, compute, video]
    tty: true
    stdin_open: true
